apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bestrong.fullname" . }}
  labels:
    app: {{ include "bestrong.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "bestrong.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "bestrong.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.environment.ASPNETCORE_ENVIRONMENT }}