{{- if .Values.blueGreen.enabled }}
# Blue Service
{{- if .Values.blueGreen.blue.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bestrong.fullname" . }}-blue
  labels:
    {{- include "bestrong.labels" . | nindent 4 }}
    app.kubernetes.io/environment: blue
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bestrong.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/environment: blue
{{- end }}

# Green Service
{{- if .Values.blueGreen.green.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bestrong.fullname" . }}-green
  labels:
    {{- include "bestrong.labels" . | nindent 4 }}
    app.kubernetes.io/environment: green
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bestrong.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/environment: green
{{- end }}
{{- else }}
# Fallback to single Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bestrong.fullname" . }}
  labels:
    {{- include "bestrong.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bestrong.selectorLabels" . | nindent 4 }}
{{- end }}