grafana:
  enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: selfsigned-issuer
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - grafana.bestrong.local
    tls:
      - hosts:
          - grafana.bestrong.local
        secretName: grafana-tls
  service:
    type: ClusterIP
  adminPassword: admin

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
