apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bestrong-selfsigned-cert
  namespace: default
spec:
  secretName: bestrong-tls
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: bestrong.local
  dnsNames:
    - bestrong.local