replicaCount: 2

image:
  repository: bestrong.azurecr.io/helm/bestrong
  tag: "158"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

environment:
  ASPNETCORE_ENVIRONMENT: Production

# Blue-Green Deployment configuration
blueGreen:
  enabled: true
  activeEnvironment: "blue" 
  blue:
    enabled: true
    image:
      tag: "158" # Blue version (stable)
  green:
    enabled: false
    image:
      tag: "159" # Green version (new)

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
  hosts:
    - host: bestrong.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: bestrong-tls
      hosts:
        - bestrong.local

tls:
  issuer: selfsigned-issuer


monitoring:
  enabled: true
  prometheus:
    resources:
      requests:
        memory: "400Mi"
        cpu: "200m"
      limits:
        memory: "800Mi"
        cpu: "500m"
  grafana:
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "200Mi"
        cpu: "200m"