# Default values for bestrong chart
replicaCount: 1

image:
  repository: bestrong.azurecr.io/bestrong-api
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

environment:
  ASPNETCORE_ENVIRONMENT: Production

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: selfsigned-issuer
  hosts:
    - host: bestrong-api.nip.io  # This will be overwritten during deployment
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: bestrong-api-tls
      hosts:
        - bestrong-api.nip.io  # This will be overwritten during deployment

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}