replicaCount: 1

image:
  repository: bestrong.azurecr.io/helm/bestrong
  tag: "158"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

environment:
  ASPNETCORE_ENVIRONMENT: Production

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
  hosts:
    - host: bestrong.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: bestrong-tls
      hosts:
        - bestrong.local

tls:
  issuer: selfsigned-issuer