# Default values for bestrong chart
replicaCount: 1

image:
  repository: bestrong.azurecr.io/bestrong-api
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

environment:
  ASPNETCORE_ENVIRONMENT: Production

ingress:
  enabled: true
  className: "nginx"


  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: bestrong.local 
      paths:
        - path: /
          pathType: Prefix
  # tls:
  #   - secretName: bestrong-api-tls
  #     hosts:
  #       - bestrong-api.nip.io  # This will be overwritten during deployment

