replicaCount: 1

image:
  repository: bestrong.azurecr.io/helm/bestrong
  tag: ""
  pullPolicy: IfNotPresent

environment:
  ASPNETCORE_ENVIRONMENT: "Production"

service:
  type: ClusterIP
  port: 80

nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    # Add additional annotations as needed
  hosts:
    - host: bestrong.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  # - secretName: bestrong-tls
  #   hosts:
  #     - bestrong.example.com