# templates/monitoring/alert-rules.yaml
{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-alerts
  namespace: {{ .Release.Namespace }}
  labels:
    role: alert-rules
spec:
  groups:
  - name: bestrong-api-alerts
    rules:
    - alert: HighCPUUsage
      expr: 100 * (rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}", pod=~"{{ .Release.Name }}-.*"}[5m]) / kube_pod_container_resource_requests_cpu_cores{namespace="{{ .Release.Namespace }}", pod=~"{{ .Release.Name }}-.*"}) > 70
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage for {{ .Release.Name }} API"
        description: "{{ .Release.Name }} API CPU usage is above 70% for 5 minutes."
    - alert: HighMemoryUsage
      expr: 100 * (container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}", pod=~"{{ .Release.Name }}-.*"} / kube_pod_container_resource_requests_memory_bytes{namespace="{{ .Release.Namespace }}", pod=~"{{ .Release.Name }}-.*"}) > 70
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High Memory usage for {{ .Release.Name }} API"
        description: "{{ .Release.Name }} API memory usage is above 70% for 5 minutes."
{{- end }}