apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: default
spec:
  secretName: bestrong-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: bestrong.local
  dnsNames:
  - bestrong.local